workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        APP_NAME: "cow_and_crop"
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Flutter clean and build
        script: |
          flutter clean
          flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - vikashguptavsg@gmail.com
